// D&D 5e Character Creation Data

export const races = [
  {
    value: "human",
    label: "Human",
    subraces: [],
    traits: ["+1 to All Ability Scores", "Extra Language", "Extra Skill"],
    abilityBonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 },
    speed: 30,
    size: "Medium",
    description: "Versatile and ambitious, humans are the most adaptable of all races.",
  },
  {
    value: "elf",
    label: "Elf",
    subraces: ["High Elf", "Wood Elf", "Dark Elf (Drow)"],
    traits: ["+2 Dexterity", "Darkvision", "Fey Ancestry", "Trance", "Keen Senses"],
    abilityBonuses: { dexterity: 2 },
    speed: 30,
    size: "Medium",
    description: "Elves are graceful beings with keen senses and a deep connection to magic.",
  },
  {
    value: "dwarf",
    label: "Dwarf",
    subraces: ["Hill Dwarf", "Mountain Dwarf"],
    traits: ["+2 Constitution", "Darkvision", "Dwarven Resilience", "Stonecunning"],
    abilityBonuses: { constitution: 2 },
    speed: 25,
    size: "Medium",
    description: "Dwarves are stout, hardy folk known for their craftsmanship and resilience.",
  },
  {
    value: "halfling",
    label: "Halfling",
    subraces: ["Lightfoot", "Stout"],
    traits: ["+2 Dexterity", "Lucky", "Brave", "Halfling Nimbleness"],
    abilityBonuses: { dexterity: 2 },
    speed: 25,
    size: "Small",
    description: "Halflings are small, cheerful folk who value comfort and community.",
  },
  {
    value: "dragonborn",
    label: "Dragonborn",
    subraces: [],
    traits: ["+2 Strength", "+1 Charisma", "Draconic Ancestry", "Breath Weapon", "Damage Resistance"],
    abilityBonuses: { strength: 2, charisma: 1 },
    speed: 30,
    size: "Medium",
    description: "Dragonborn are proud, dragon-blooded warriors with a breath weapon.",
  },
  {
    value: "gnome",
    label: "Gnome",
    subraces: ["Forest Gnome", "Rock Gnome"],
    traits: ["+2 Intelligence", "Darkvision", "Gnome Cunning"],
    abilityBonuses: { intelligence: 2 },
    speed: 25,
    size: "Small",
    description: "Gnomes are inventive and curious, with a natural affinity for illusion magic.",
  },
  {
    value: "half-elf",
    label: "Half-Elf",
    subraces: [],
    traits: ["+2 Charisma", "+1 to Two Others", "Darkvision", "Fey Ancestry", "Two Extra Skills"],
    abilityBonuses: { charisma: 2 },
    speed: 30,
    size: "Medium",
    description: "Half-elves combine human ambition with elven grace and versatility.",
  },
  {
    value: "half-orc",
    label: "Half-Orc",
    subraces: [],
    traits: ["+2 Strength", "+1 Constitution", "Darkvision", "Menacing", "Relentless Endurance", "Savage Attacks"],
    abilityBonuses: { strength: 2, constitution: 1 },
    speed: 30,
    size: "Medium",
    description: "Half-orcs are powerful warriors who channel their orcish fury in battle.",
  },
  {
    value: "tiefling",
    label: "Tiefling",
    subraces: [],
    traits: ["+2 Charisma", "+1 Intelligence", "Darkvision", "Hellish Resistance", "Infernal Legacy"],
    abilityBonuses: { charisma: 2, intelligence: 1 },
    speed: 30,
    size: "Medium",
    description: "Tieflings bear the mark of infernal heritage, granting them innate magic.",
  },
]

export const subraces: Record<string, { label: string; abilityBonuses: Record<string, number>; traits: string[] }[]> = {
  elf: [
    {
      label: "High Elf",
      abilityBonuses: { intelligence: 1 },
      traits: ["+1 Intelligence", "Cantrip", "Extra Language"],
    },
    { label: "Wood Elf", abilityBonuses: { wisdom: 1 }, traits: ["+1 Wisdom", "Fleet of Foot", "Mask of the Wild"] },
    {
      label: "Dark Elf (Drow)",
      abilityBonuses: { charisma: 1 },
      traits: ["+1 Charisma", "Superior Darkvision", "Drow Magic"],
    },
  ],
  dwarf: [
    { label: "Hill Dwarf", abilityBonuses: { wisdom: 1 }, traits: ["+1 Wisdom", "Dwarven Toughness"] },
    { label: "Mountain Dwarf", abilityBonuses: { strength: 2 }, traits: ["+2 Strength", "Dwarven Armor Training"] },
  ],
  halfling: [
    { label: "Lightfoot", abilityBonuses: { charisma: 1 }, traits: ["+1 Charisma", "Naturally Stealthy"] },
    { label: "Stout", abilityBonuses: { constitution: 1 }, traits: ["+1 Constitution", "Stout Resilience"] },
  ],
  gnome: [
    {
      label: "Forest Gnome",
      abilityBonuses: { dexterity: 1 },
      traits: ["+1 Dexterity", "Natural Illusionist", "Speak with Small Beasts"],
    },
    {
      label: "Rock Gnome",
      abilityBonuses: { constitution: 1 },
      traits: ["+1 Constitution", "Artificer's Lore", "Tinker"],
    },
  ],
}

export const classes = [
  {
    value: "barbarian",
    label: "Barbarian",
    icon: "⚔️",
    description: "A fierce warrior of primitive background who can enter a battle rage",
    hitDie: "d12",
    primaryAbility: "Strength",
    savingThrows: ["Strength", "Constitution"],
    armorWeapons: "Light/Medium Armor, Shields, Simple/Martial Weapons",
  },
  {
    value: "bard",
    label: "Bard",
    icon: "🎭",
    description: "An inspiring magician whose power echoes the music of creation",
    hitDie: "d8",
    primaryAbility: "Charisma",
    savingThrows: ["Dexterity", "Charisma"],
    armorWeapons: "Light Armor, Simple Weapons, Hand Crossbows, Longswords, Rapiers, Shortswords",
  },
  {
    value: "cleric",
    label: "Cleric",
    icon: "✨",
    description: "A priestly champion who wields divine magic in service of a higher power",
    hitDie: "d8",
    primaryAbility: "Wisdom",
    savingThrows: ["Wisdom", "Charisma"],
    armorWeapons: "Light/Medium Armor, Shields, Simple Weapons",
  },
  {
    value: "druid",
    label: "Druid",
    icon: "🌿",
    description: "A priest of the Old Faith, wielding the powers of nature",
    hitDie: "d8",
    primaryAbility: "Wisdom",
    savingThrows: ["Intelligence", "Wisdom"],
    armorWeapons:
      "Light/Medium Armor (nonmetal), Shields (nonmetal), Clubs, Daggers, Darts, Javelins, Maces, Quarterstaffs, Scimitars, Sickles, Slings, Spears",
  },
  {
    value: "fighter",
    label: "Fighter",
    icon: "🛡️",
    description: "A master of martial combat, skilled with a variety of weapons and armor",
    hitDie: "d10",
    primaryAbility: "Strength or Dexterity",
    savingThrows: ["Strength", "Constitution"],
    armorWeapons: "All Armor, Shields, Simple/Martial Weapons",
  },
  {
    value: "monk",
    label: "Monk",
    icon: "👊",
    description: "A master of martial arts, harnessing the power of body and soul",
    hitDie: "d8",
    primaryAbility: "Dexterity & Wisdom",
    savingThrows: ["Strength", "Dexterity"],
    armorWeapons: "Simple Weapons, Shortswords",
  },
  {
    value: "paladin",
    label: "Paladin",
    icon: "⚜️",
    description: "A holy warrior bound to a sacred oath",
    hitDie: "d10",
    primaryAbility: "Strength & Charisma",
    savingThrows: ["Wisdom", "Charisma"],
    armorWeapons: "All Armor, Shields, Simple/Martial Weapons",
  },
  {
    value: "ranger",
    label: "Ranger",
    icon: "🏹",
    description: "A warrior who uses martial prowess and nature magic to combat threats",
    hitDie: "d10",
    primaryAbility: "Dexterity & Wisdom",
    savingThrows: ["Strength", "Dexterity"],
    armorWeapons: "Light/Medium Armor, Shields, Simple/Martial Weapons",
  },
  {
    value: "rogue",
    label: "Rogue",
    icon: "🗡️",
    description: "A scoundrel who uses stealth and trickery to overcome obstacles",
    hitDie: "d8",
    primaryAbility: "Dexterity",
    savingThrows: ["Dexterity", "Intelligence"],
    armorWeapons: "Light Armor, Simple Weapons, Hand Crossbows, Longswords, Rapiers, Shortswords",
  },
  {
    value: "sorcerer",
    label: "Sorcerer",
    icon: "🔮",
    description: "A spellcaster who draws on inherent magic from a gift or bloodline",
    hitDie: "d6",
    primaryAbility: "Charisma",
    savingThrows: ["Constitution", "Charisma"],
    armorWeapons: "Daggers, Darts, Slings, Quarterstaffs, Light Crossbows",
  },
  {
    value: "warlock",
    label: "Warlock",
    icon: "👁️",
    description: "A wielder of magic derived from a bargain with an extraplanar entity",
    hitDie: "d8",
    primaryAbility: "Charisma",
    savingThrows: ["Wisdom", "Charisma"],
    armorWeapons: "Light Armor, Simple Weapons",
  },
  {
    value: "wizard",
    label: "Wizard",
    icon: "📚",
    description: "A scholarly magic-user capable of manipulating the structures of reality",
    hitDie: "d6",
    primaryAbility: "Intelligence",
    savingThrows: ["Intelligence", "Wisdom"],
    armorWeapons: "Daggers, Darts, Slings, Quarterstaffs, Light Crossbows",
  },
]

export const backgrounds = [
  {
    value: "acolyte",
    label: "Acolyte",
    description: "You have spent your life in service to a temple, learning sacred rites and providing sacrifices.",
    skillProficiencies: ["Insight", "Religion"],
    languages: 2,
    equipment: "Holy symbol, prayer book, 5 sticks of incense, vestments, common clothes, 15 gp",
    feature: "Shelter of the Faithful",
  },
  {
    value: "charlatan",
    label: "Charlatan",
    description:
      "You have always had a way with people. You know what makes them tick and can tease out their desires.",
    skillProficiencies: ["Deception", "Sleight of Hand"],
    toolProficiencies: ["Disguise kit", "Forgery kit"],
    equipment: "Fine clothes, disguise kit, tools of the con, 15 gp",
    feature: "False Identity",
  },
  {
    value: "criminal",
    label: "Criminal",
    description: "You are an experienced criminal with a history of breaking the law and surviving by your wits.",
    skillProficiencies: ["Deception", "Stealth"],
    toolProficiencies: ["Gaming set", "Thieves' tools"],
    equipment: "Crowbar, dark common clothes with hood, 15 gp",
    feature: "Criminal Contact",
  },
  {
    value: "entertainer",
    label: "Entertainer",
    description: "You thrive in front of an audience. You know how to entrance, entertain, and inspire.",
    skillProficiencies: ["Acrobatics", "Performance"],
    toolProficiencies: ["Disguise kit", "Musical instrument"],
    equipment: "Musical instrument, favor of an admirer, costume, 15 gp",
    feature: "By Popular Demand",
  },
  {
    value: "folk-hero",
    label: "Folk Hero",
    description: "You come from humble origins but are destined for greatness. People see you as their champion.",
    skillProficiencies: ["Animal Handling", "Survival"],
    toolProficiencies: ["Artisan's tools", "Vehicles (land)"],
    equipment: "Artisan's tools, shovel, iron pot, common clothes, 10 gp",
    feature: "Rustic Hospitality",
  },
  {
    value: "guild-artisan",
    label: "Guild Artisan",
    description: "You are a member of an artisan's guild, skilled in a particular craft and connected to merchants.",
    skillProficiencies: ["Insight", "Persuasion"],
    toolProficiencies: ["Artisan's tools"],
    languages: 1,
    equipment: "Artisan's tools, letter of introduction from guild, traveler's clothes, 15 gp",
    feature: "Guild Membership",
  },
  {
    value: "hermit",
    label: "Hermit",
    description: "You lived in seclusion for an extended period, contemplating the nature of existence.",
    skillProficiencies: ["Medicine", "Religion"],
    toolProficiencies: ["Herbalism kit"],
    languages: 1,
    equipment: "Scroll case with notes, winter blanket, common clothes, herbalism kit, 5 gp",
    feature: "Discovery",
  },
  {
    value: "noble",
    label: "Noble",
    description: "You understand wealth, power, and privilege. You carry a noble title and command respect.",
    skillProficiencies: ["History", "Persuasion"],
    toolProficiencies: ["Gaming set"],
    languages: 1,
    equipment: "Fine clothes, signet ring, scroll of pedigree, 25 gp",
    feature: "Position of Privilege",
  },
  {
    value: "outlander",
    label: "Outlander",
    description: "You grew up in the wilds, far from civilization. The wilderness is in your blood.",
    skillProficiencies: ["Athletics", "Survival"],
    toolProficiencies: ["Musical instrument"],
    languages: 1,
    equipment: "Staff, hunting trap, trophy from animal, traveler's clothes, 10 gp",
    feature: "Wanderer",
  },
  {
    value: "sage",
    label: "Sage",
    description: "You spent years learning the lore of the multiverse. You scoured manuscripts and studied.",
    skillProficiencies: ["Arcana", "History"],
    languages: 2,
    equipment: "Bottle of ink, quill, small knife, letter from colleague, common clothes, 10 gp",
    feature: "Researcher",
  },
  {
    value: "sailor",
    label: "Sailor",
    description: "You sailed on a seagoing vessel for years. You've weathered storms and faced sea monsters.",
    skillProficiencies: ["Athletics", "Perception"],
    toolProficiencies: ["Navigator's tools", "Vehicles (water)"],
    equipment: "Belaying pin (club), 50 ft silk rope, lucky charm, common clothes, 10 gp",
    feature: "Ship's Passage",
  },
  {
    value: "soldier",
    label: "Soldier",
    description: "War has been your life for as long as you care to remember. You trained as a youth.",
    skillProficiencies: ["Athletics", "Intimidation"],
    toolProficiencies: ["Gaming set", "Vehicles (land)"],
    equipment: "Insignia of rank, trophy from fallen enemy, gaming set, common clothes, 10 gp",
    feature: "Military Rank",
  },
  {
    value: "urchin",
    label: "Urchin",
    description: "You grew up on the streets alone, orphaned, and poor. You learned to survive on your own.",
    skillProficiencies: ["Sleight of Hand", "Stealth"],
    toolProficiencies: ["Disguise kit", "Thieves' tools"],
    equipment: "Small knife, map of your home city, pet mouse, token from parents, common clothes, 10 gp",
    feature: "City Secrets",
  },
]

export const alignments = [
  ["Lawful Good", "Neutral Good", "Chaotic Good"],
  ["Lawful Neutral", "True Neutral", "Chaotic Neutral"],
  ["Lawful Evil", "Neutral Evil", "Chaotic Evil"],
]

export const abilities = [
  { key: "strength", label: "Strength", abbr: "STR" },
  { key: "dexterity", label: "Dexterity", abbr: "DEX" },
  { key: "constitution", label: "Constitution", abbr: "CON" },
  { key: "intelligence", label: "Intelligence", abbr: "INT" },
  { key: "wisdom", label: "Wisdom", abbr: "WIS" },
  { key: "charisma", label: "Charisma", abbr: "CHA" },
]

export const standardArray = [15, 14, 13, 12, 10, 8]

export const skills = [
  { name: "Acrobatics", ability: "DEX" },
  { name: "Animal Handling", ability: "WIS" },
  { name: "Arcana", ability: "INT" },
  { name: "Athletics", ability: "STR" },
  { name: "Deception", ability: "CHA" },
  { name: "History", ability: "INT" },
  { name: "Insight", ability: "WIS" },
  { name: "Intimidation", ability: "CHA" },
  { name: "Investigation", ability: "INT" },
  { name: "Medicine", ability: "WIS" },
  { name: "Nature", ability: "INT" },
  { name: "Perception", ability: "WIS" },
  { name: "Performance", ability: "CHA" },
  { name: "Persuasion", ability: "CHA" },
  { name: "Religion", ability: "INT" },
  { name: "Sleight of Hand", ability: "DEX" },
  { name: "Stealth", ability: "DEX" },
  { name: "Survival", ability: "WIS" },
]

export const languages = [
  "Common",
  "Dwarvish",
  "Elvish",
  "Giant",
  "Gnomish",
  "Goblin",
  "Halfling",
  "Orc",
  "Abyssal",
  "Celestial",
  "Draconic",
  "Deep Speech",
  "Infernal",
  "Primordial",
  "Sylvan",
  "Undercommon",
]

export const toolProficiencies = [
  "Alchemist's Supplies",
  "Brewer's Supplies",
  "Calligrapher's Supplies",
  "Carpenter's Tools",
  "Cartographer's Tools",
  "Cobbler's Tools",
  "Cook's Utensils",
  "Glassblower's Tools",
  "Jeweler's Tools",
  "Leatherworker's Tools",
  "Mason's Tools",
  "Painter's Supplies",
  "Potter's Tools",
  "Smith's Tools",
  "Tinker's Tools",
  "Weaver's Tools",
  "Woodcarver's Tools",
  "Disguise Kit",
  "Forgery Kit",
  "Gaming Set",
  "Herbalism Kit",
  "Musical Instrument",
  "Navigator's Tools",
  "Poisoner's Kit",
  "Thieves' Tools",
]

export const equipmentPackages = {
  barbarian: [
    { name: "Greataxe", selected: true },
    { name: "Two Handaxes", selected: false },
    { name: "Explorer's Pack", selected: true },
    { name: "Four Javelins", selected: true },
  ],
  fighter: [
    { name: "Chain Mail", selected: true },
    { name: "Leather Armor, Longbow, 20 Arrows", selected: false },
    { name: "Martial Weapon and Shield", selected: true },
    { name: "Two Martial Weapons", selected: false },
    { name: "Light Crossbow and 20 Bolts", selected: true },
    { name: "Two Handaxes", selected: false },
    { name: "Dungeoneer's Pack", selected: true },
    { name: "Explorer's Pack", selected: false },
  ],
  wizard: [
    { name: "Quarterstaff", selected: true },
    { name: "Dagger", selected: false },
    { name: "Component Pouch", selected: true },
    { name: "Arcane Focus", selected: false },
    { name: "Scholar's Pack", selected: true },
    { name: "Explorer's Pack", selected: false },
    { name: "Spellbook", selected: true },
  ],
  default: [
    { name: "Simple Weapon", selected: true },
    { name: "Explorer's Pack", selected: true },
    { name: "Basic Adventuring Gear", selected: true },
  ],
}

export const startingGold = {
  barbarian: "2d4 × 10 gp",
  bard: "5d4 × 10 gp",
  cleric: "5d4 × 10 gp",
  druid: "2d4 × 10 gp",
  fighter: "5d4 × 10 gp",
  monk: "5d4 gp",
  paladin: "5d4 × 10 gp",
  ranger: "5d4 × 10 gp",
  rogue: "4d4 × 10 gp",
  sorcerer: "3d4 × 10 gp",
  warlock: "4d4 × 10 gp",
  wizard: "4d4 × 10 gp",
}

export const personalitySuggestions = {
  acolyte: {
    traits: ["I idolize a particular hero of my faith.", "I can find common ground between the fiercest enemies."],
    ideals: [
      "Tradition. The ancient traditions of worship must be preserved.",
      "Charity. I always try to help those in need.",
    ],
    bonds: ["I would die to recover an ancient relic of my faith.", "I owe my life to the priest who took me in."],
    flaws: [
      "I judge others harshly, and myself even more severely.",
      "I put too much trust in those who wield power within my temple's hierarchy.",
    ],
  },
  soldier: {
    traits: ["I'm always polite and respectful.", "I've lost too many friends, and I'm slow to make new ones."],
    ideals: [
      "Greater Good. Our lot is to lay down our lives in defense of others.",
      "Honor. I never abandon my companions.",
    ],
    bonds: ["Someone saved my life on the battlefield.", "I fight for those who cannot fight for themselves."],
    flaws: [
      "I made a terrible mistake in battle that cost many lives.",
      "I obey the law, even if the law causes misery.",
    ],
  },
  default: {
    traits: ["I am curious about everything.", "I enjoy meeting new people and making friends."],
    ideals: [
      "Freedom. Everyone should be free to pursue their own destiny.",
      "Knowledge. The path to power is through understanding.",
    ],
    bonds: ["I protect those who cannot protect themselves.", "I seek to prove myself worthy of my mentor's faith."],
    flaws: ["I have trouble keeping my true feelings hidden.", "I am too curious for my own good."],
  },
}
